import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/Header'
import Footer from '@/Footer'
import Menu from '@/Menu'
import 'bootstrap/dist/css/bootstrap.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>/
       <Header/>
       <Menu/>
       {children}
       <Footer/>
       
        {children}
        </body>
    </html>
  )
}
